Repository fga-eps-mds/2022-2-EuPescador-Doc, pull requests merged in 2022-12, with the labels that each got.

#25 Criação de uma logo para a aplicação
  docs/assets/logo/logoNova.png
  docs/assets/logo/logo_vet.svg
  docs/assets/logo/modelosLogo.png
  docs/produto/identidade_visual.md
  mkdocs.yml
Labels: design

#26 add ata 30-11
  docs/atas/reuniao-com-time/ata_29_11_22.md
  docs/atas/reuniao-com-time/ata_30_11_22.md
  mkdocs.yml
Labels: documentation, management

#57 Documento de arquitetura
  docs/assets/produto/Arquitetura.png
  docs/produto/arquitetura.md
  docs/produto/eap.md
  mkdocs.yml
Labels: documentation

#64 #63 Ajustes da wiki
  docs/assets/docs/backlog-2.png
  docs/assets/produto/Backlog.png
  docs/atas/reuniao-com-time/ata_23_11_22.md
  docs/organizacao/riscos.md
  docs/produto/arquitetura.md
  docs/produto/backlog.md
  mkdocs.yml
Labels: documentation

#56 #55 Protótipo de Alta Fidelidade Mobile
  docs/produto/prototipos.md
  mkdocs.yml
Labels: mobile, design

#70 #69 Adiciona sprint 1 na wiki
  docs/sprints/sprint-1.md
  mkdocs.yml
Labels: documentation

#82 79 Complementar identidade visual
  docs/assets/produto/cores.png
  docs/assets/produto/simbologia.png
  docs/assets/produto/tipografia.png
  docs/assets/produto/variacoes_logo.png
  docs/produto/identidade_visual.md
Labels: web, mobile, design
